config/routes.rb
Rubymine::Application.routes.draw do
  devise_for :users
  get "site/index"
  get "site/about"
  get "site/contact"
  get "site/feature"
  get "site/category"

   root 'site#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def feature
  end

  def category
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/_header.html.erb
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Topsite.com", root_path %></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
		 <!--    <ul class="left">
		      <li class="active"><a href="#">Right Nav Button Active</a></li>
		      <li class="has-dropdown">
		        <a href="#">Right Button with Dropdown</a>
		        <ul class="dropdown">
		          <li><a href="#">First link in dropdown</a></li>
		        </ul>
		      </li>
		    </ul>
		 -->
    <!-- Left Nav Section -->
    <ul class="right">
      <li><%= link_to "Home", root_path%></li>
      <li><%= link_to "Features", site_feature_path%></li>
	  <li><%= link_to "Category", site_category_path%></li>
      <li><%= link_to "About", site_about_path%></li>
      <li><%= link_to "Conatct", site_contact_path%></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/site/about.html.erb
<h1>Site#about</h1>
<p>Find me in app/views/site/about.html.erb</p>

app/views/site/category.html.erb
<h1>Site#category</h1>
<p>Find me in app/views/site/category.html.erb</p>

app/views/site/contact.html.erb
<h1>Site#contact</h1>
<p>Find me in app/views/site/contact.html.erb</p>

app/views/site/feature.html.erb
<h1>Site#feature</h1>
<p>Find me in app/views/site/feature.html.erb</p>

app/views/site/index.html.erb
<div class="row" id="head">
	<div class="large-12 columns text-center good">
		<!-- <div id="tweeter" class="text-center smargin smargin-top secondary">
			<em>@AdamPietrasiak: I've just discovered amazing way to developed wensite in no time</em>
		</div> -->
		<h1 class="bmargin tmargin">Welcome to Topsite.com</h1>
		<%= image_tag "image-rails.png", size: "300x300"%>
	</div>
</div>
<div class="row inner pos-rel">
	<div class="large-12 columns text-center mmargin mmargin-top">
		<h2>What do you want to learn?</h2>
		<h4 class="slim secondary">
			That's new programing for Web Development 
		</h4>
	</div>
	<div class="down-triangle"></div>
</div>
<div class="row" id="about">
	<div class="large-12 columns nmargin-top nmargin text-center">
		<div class="large-3 small-6 columns style-hover team-single">
			<%= image_tag "ruby-icon.png" %>
			<h3>Ruby</h3>
		</div>
		<div class="large-3 small-6 columns style-hover team-single">
			<%= image_tag "rails-icon.png" %>
			<h3>Rails</h3>
		</div>
		<div class="large-3 small-6 columns style-hover team-single">
			<%= image_tag "sass-icon.png" %>
			<h3>Sass</h3>
		</div>
		<div class="large-3 small-6 columns style-hover team-single">
			<%= image_tag "cff-icon.png" %>
			<h3>Coffeescript</h3>
		</div>
		<div class="row">
			<div class="large-12 columns text-center">
				<h3 class="slim-title">I'm <em>Seyha</em></h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio, animi consectetur dolorum similique odio nesciunt iste nam magni eius laborum maxime molestiae accusamus doloribus culpa quibusdam minus aliquid est maiores.</p>
			</div>
			<div class="large-12 columns">
				<div class="large-4 columns"></div>
				<div class="large-4 large-offset-4 columns good">
					<p class="slim-title style-hover"><%= image_tag("qq.png") %></p>
				</div>
				<div class="large-4 columns"></div>
			</div>
		</div>
	</div>
</div>
<div id="contact">
	<div class="row">
		<div class="large-8 large-offset-2 columns nmargin nargin-top">
			<div class="control-foot">
			<h2>Contact us</h2>
				<p class="tertiry">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis,<br>
				</p>
				<p>Laboriosam culpa ducimus quasi nobis. Quos, voluptas sunt illo soluta molestias nemo accusantium nostrum obcaecati veritatis? Quos, cumque ut quibusdam minus ullam?</p>
			</div>	
			<div class="large-6 columns"><input class="trans" type="text" placeholder="Your Name..."></div>
			<div class="large-6 columns"><input class="trans" type="text" placeholder="Your Email..."></div>
			<div class="large-6 columns"><input class="trans" type="text" placeholder="City..."></div>
			<div class="large-6 columns"><input class="trans" type="text" placeholder="Topic..."></div>
		   <div class="large-12 columns"><textarea name="" id="" cols="30" rows="7" placeholder="Content"></div>
		   <a href="" class="tiny button">Submit</a>
		</div>
	</div>
</div>